spring:
  application:
    name: ImoocMerchants
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527

logging:
  level:
    com.imooc.merchants: debug
  file: imooc-merchants.log